baseURL                   = "https://ashwingoel.com"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3
hrefTargetBlank            = true

theme                      = "AllinOne"
title                      = "Ashwin Goel"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:slug/"


[taxonomies]
  tag                      = "tags"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"

  [[menu.main]]
    name                   = "Resume"
    weight                 = -110
    identifier             = "resume"
    url                    = "https://drive.google.com/file/d/1uGt8VKNt-rQZEPJTUaSpfhjs_iDoKFRU/view?usp=sharing"

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"



[params]
  faviconfile              = "img/Ashwin-Goel-logo.jpg"               # from static/
  avatar                   = "img/Ashwin-Goel-profile.jpg"             # path to image in static dir e.g img/avatar.png
  author                   = "Ashwin Goel"
  description              = ["Aspiring Software Developer"]          # appears in the site header when set to a non-empty string
  welcome_head             = ""
  welcome_word             = ""

  latestpostscount         = 5                           # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "goelashwin36@gmail.com"
  github                   = "//github.com/goelashwin36"
  linkedin                 = "//linkedin.com/in/ashwingoel"
  medium                   = "//medium.com/@goelashwin36"
  facebook                 = "//facebook.com/ashwingoel36"
  twitter                  = "//twitter.com/ashwingoel36"
  instagram                = "//instagram.com/_ashwin_g_"
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon

  # analytics
  googleAnalytics          = "UA-140853249-1"
